### ISSUE TITLE
Data download cancellation should close all files

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate#352]
### Expected behavior

After cancellation a dataset download, all related files should be closed.

### Actual behavior

Files seem to remain open (on Windows), so I can't restart the download, e.g. with or w/o constraints.

![image](https://user-images.githubusercontent.com/206773/30167453-bb30ec50-93e6-11e7-990a-3e60df8a04aa.png)

### Steps to reproduce the problem

1. **DATA SOURCES* panel, *Download* dataset
2. **TASKS** panel, press *Cancel*
3. Download again, with or w/o constraints

### Specifications 

Cate Core + Desktop 0.9 dev 7 on Windows 10

**Comment by forman** [comment]
Full stack trace:

Cate Desktop, version 0.9.0-dev.7

make_ds_local() call raised exception: "Cannot access data source local.esacci.OC.day.L3S.IOP.multi-sensor.multi-platform.MERGED.2-0.2011-r1, another process is using it (pid:4828"

An error (code 20) occurred while executing a backend process:

Traceback (most recent call last):
  File "C:\Users\Norman\IdeaProjects\ccitools\cate-core\cate\util\web\jsonrpchandler.py", line 190, in send_service_method_result
    result = future.result()
  File "C:\Users\Norman\Miniconda3\envs\cate\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "C:\Users\Norman\Miniconda3\envs\cate\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "C:\Users\Norman\Miniconda3\envs\cate\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Norman\IdeaProjects\ccitools\cate-core\cate\util\web\jsonrpchandler.py", line 267, in call_service_method
    result = method(*method_params, monitor=monitor)
  File "C:\Users\Norman\IdeaProjects\ccitools\cate-core\cate\webapi\websocket.py", line 193, in make_ds_local
    monitor=monitor.child(98))
  File "C:\Users\Norman\IdeaProjects\ccitools\cate-core\cate\ds\esa_cci_odp.py", line 899, in make_local
    time_range, var_names, meta_info=local_meta_info, lock_file=True)
  File "C:\Users\Norman\IdeaProjects\ccitools\cate-core\cate\ds\local.py", line 613, in create_data_source
    .format(ds.id, writer_pid))
ValueError: Cannot access data source local.esacci.OC.day.L3S.IOP.multi-sensor.multi-platform.MERGED.2-0.2011-r1, another process is using it (pid:4828

**Comment by forman** [comment]
https://github.com/CCI-Tools/cate-core/blob/bd92761b4e00bffa7e87359980b56f0c4872beb2/cate/ds/local.py#L611-L613

**Comment by forman** [comment]
Weird, because there should only be a single process.

**Comment by kbernat** [comment]
Yes... I have to analyse it. Never tried it in GUI

**Comment by kbernat** [comment]
In CLI after cancellation (or crash) process no longer exists.. So resume "call" will have new PID.

**Comment by forman** [comment]
@kbernat is this fixed or are you working on this (because it is in "Doing")?
