### ISSUE TITLE
Error downloading same dataset once more

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate#415]
_From @forman on June 28, 2017 10:43_

Cate Desktop, version 0.8.0-rc.7.dev.2

Multiple data sources with the name "esacci.SEAICE.day.L4.SICONC.multi-sensor.multi-platform.AMSR_50kmEASE2.2-0.NH" found

An error (code 10) occurred while executing a backend process:

Traceback (most recent call last):
  File "C:\Users\Norman\IdeaProjects\ccitools\cate-core\cate\util\web\jsonrpchandler.py", line 163, in send_service_method_result
    result = future.result()
  File "C:\Users\Norman\Miniconda3\envs\cate\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "C:\Users\Norman\Miniconda3\envs\cate\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "C:\Users\Norman\Miniconda3\envs\cate\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Norman\IdeaProjects\ccitools\cate-core\cate\util\web\jsonrpchandler.py", line 216, in call_service_method
    result = method(*method_params, monitor=monitor)
  File "C:\Users\Norman\IdeaProjects\ccitools\cate-core\cate\webapi\websocket.py", line 183, in make_ds_local
    raise ValueError('Multiple data sources with the name "%s" found' % data_source_name)
ValueError: Multiple data sources with the name "esacci.SEAICE.day.L4.SICONC.multi-sensor.multi-platform.AMSR_50kmEASE2.2-0.NH" found

_Copied from original issue: CCI-Tools/cate-desktop#22_

**Comment by forman** [comment]
Not sure if this still applies

**Comment by kbernat** [comment]
Fixed by introduction of unique identifiers for each dataset. #277
