### ISSUE TITLE
Opening a single file leads to error in normalization

### ISSUE THREAD

**Issue by mzuehlke** [CCI-Tools/cate#433]
### Expected behavior

User should be able to open data sources that consist of only a single file or adjusting the time constraint in a way that only a single file matches.

### Actual behavior
   
    Traceback (most recent call last):
      File "/home/marcoz/Projects/BC/PyBc/cci-tools/cate-core/cate/util/web/jsonrpchandler.py", line 192, in send_service_method_result
        result = future.result()
      File "/home/marcoz/Projects/Anaconda/miniconda3/envs/cate/lib/python3.6/concurrent/futures/_base.py", line 398, in result
        return self.__get_result()
      File "/home/marcoz/Projects/Anaconda/miniconda3/envs/cate/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
        raise self._exception
      File "/home/marcoz/Projects/Anaconda/miniconda3/envs/cate/lib/python3.6/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/marcoz/Projects/BC/PyBc/cci-tools/cate-core/cate/util/web/jsonrpchandler.py", line 269, in call_service_method
        result = method(*method_params, monitor=monitor)
      File "/home/marcoz/Projects/BC/PyBc/cci-tools/cate-core/cate/webapi/websocket.py", line 282, in set_workspace_resource
        monitor=monitor)
      File "/home/marcoz/Projects/BC/PyBc/cci-tools/cate-core/cate/core/wsmanag.py", line 321, in set_workspace_resource
        workspace.execute_workflow(res_name=res_name, monitor=monitor)
      File "/home/marcoz/Projects/BC/PyBc/cci-tools/cate-core/cate/core/workspace.py", line 627, in execute_workflow
        self.workflow.invoke_steps(steps, context=self._new_context(), monitor=monitor)
      File "/home/marcoz/Projects/BC/PyBc/cci-tools/cate-core/cate/core/workflow.py", line 624, in invoke_steps
        steps[0].invoke(context=context, monitor=monitor)
      File "/home/marcoz/Projects/BC/PyBc/cci-tools/cate-core/cate/core/workflow.py", line 315, in invoke
        self._invoke_impl(_new_context(context, step=self), monitor=monitor)
      File "/home/marcoz/Projects/BC/PyBc/cci-tools/cate-core/cate/core/workflow.py", line 977, in _invoke_impl
        return_value = self._op(monitor=monitor, **input_values)
      File "/home/marcoz/Projects/BC/PyBc/cci-tools/cate-core/cate/core/op.py", line 211, in __call__
        return_value = self._wrapped_op(**input_values)
      File "/home/marcoz/Projects/BC/PyBc/cci-tools/cate-core/cate/ops/io.py", line 83, in open_dataset
        return adjust_temporal_attrs(normalize_op(ds))
      File "/home/marcoz/Projects/BC/PyBc/cci-tools/cate-core/cate/core/op.py", line 211, in __call__
        return_value = self._wrapped_op(**input_values)
      File "/home/marcoz/Projects/BC/PyBc/cci-tools/cate-core/cate/ops/normalize.py", line 97, in adjust_temporal_attrs
        return adjust_temporal_attrs_impl(ds)
      File "/home/marcoz/Projects/BC/PyBc/cci-tools/cate-core/cate/util/opimpl.py", line 224, in adjust_temporal_attrs_impl
        ds.attrs['time_coverage_resolution'] = _get_temporal_res(ds.time.values)
      File "/home/marcoz/Projects/BC/PyBc/cci-tools/cate-core/cate/util/opimpl.py", line 286, in _get_temporal_res
        delta = time[1] - time[0]
    IndexError: index 1 is out of bounds for axis 0 with size 1

### Steps to reproduce the problem

1. use `read_netcdf` operation to open a single netCDF

### Specifications 

1.0.0.dev1

**Comment by JanisGailis** [comment]
I can confirm that the same error (of course) appears when trying to select a single time slice of an already opened dataset.

On it.

**Comment by forman** [comment]
What if you use `read_netcdf` operation? I guess we don't normalize at all.

**Comment by JanisGailis** [comment]
Well, ``read_netcdf`` likely works, but then, that's besides the point. Temporal variable adjustment should not fail with an exception when a dataset with a single slice is passed to it. It should try to use ``time_bnds`` to determine the resolution and duration, or if that's not possible, just drop the variables it can't determine.
