### ISSUE TITLE
Operations not loaded on OS X

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate#445]
### Expected behavior

The list of operation shall be loaded into Cate Desktop.

### Actual behavior

The list of operation cannot be loaded into Cate Desktop as there is an exception due to an undefined op input:

    OperationAPI.ts:16 Uncaught TypeError: Cannot read property 'map' of undefined
        at responseOperationToOperation (/Users/forman/Projects/cate-desktop/app/renderer/webapi/apis/OperationAPI.js:13:26)
        at Array.map (native)
        at JobImpl.responseToOperation [as transformer] (/Users/forman/Projects/cate-desktop/app/renderer/webapi/apis/OperationAPI.js:4:52)
        at JobImpl.notifyDone (/Users/forman/Projects/cate-desktop/app/renderer/webapi/WebAPIClient.js:218:52)
        at WebAPIClientImpl.processMessage (/Users/forman/Projects/cate-desktop/app/renderer/webapi/WebAPIClient.js:122:17)
        at WebSocket.WebAPIClientImpl.socket.onmessage (/Users/forman/Projects/cate-desktop/app/renderer/webapi/WebAPIClient.js:71:18)

[webconsole.log](https://github.com/CCI-Tools/cate/files/1347102/webconsole.log)

### Specifications 

Cate 0.9.0.dev7 
OS X Yosemite 10.10.5

**Comment by forman** [comment]
Configuration messed up
