### ISSUE TITLE
Cate-desktop build fails on Windows 10 and node v8.6.0

### ISSUE THREAD

**Issue by kbernat** [CCI-Tools/cate#451]
### Expected behavior

Build and Install cate-desktop without errors

### Actual behavior

npm install returns error

```
11500 verbose type OperationalError
11501 verbose stack Error: sha512-WfG/X9+oATh81XtllIo/I8gOiY9EXRdv1cQdyykeXK17YcUW3EXUAi2To4pcH6nZtJPr7ZOpM5OMyWJZm+8Rsg== integrity checksum failed when using sha512: wanted sha512-WfG/X9+oATh81XtllIo/I8gOiY9EXRdv1cQdyykeXK17YcUW3EXUAi2To4pcH6nZtJPr7ZOpM5OMyWJZm+8Rsg== but got sha512-djZqUu9o06JX25fyQ/I6Rx8pIqc6mFxyP2sOYUHSLKyHgl2himz83q1vsYb3Xk2+391SidS+iNBlW50Q321Pow==. (13271 bytes)
11501 verbose stack     at Transform.on (C:\Program Files\nodejs\node_modules\npm\node_modules\ssri\index.js:275:19)
11501 verbose stack     at emitNone (events.js:110:20)
11501 verbose stack     at Transform.emit (events.js:207:7)
11501 verbose stack     at endReadableNT (_stream_readable.js:1059:12)
11501 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:138:11)
11501 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
11502 verbose cwd D:\cate-git\cate-desktop
11503 verbose Windows_NT 10.0.15063
11504 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
11505 verbose node v8.6.0
11506 verbose npm  v5.3.0
11507 error code EINTEGRITY
11508 error sha512-WfG/X9+oATh81XtllIo/I8gOiY9EXRdv1cQdyykeXK17YcUW3EXUAi2To4pcH6nZtJPr7ZOpM5OMyWJZm+8Rsg== integrity checksum failed when using sha512: wanted sha512-WfG/X9+oATh81XtllIo/I8gOiY9EXRdv1cQdyykeXK17YcUW3EXUAi2To4pcH6nZtJPr7ZOpM5OMyWJZm+8Rsg== but got sha512-djZqUu9o06JX25fyQ/I6Rx8pIqc6mFxyP2sOYUHSLKyHgl2himz83q1vsYb3Xk2+391SidS+iNBlW50Q321Pow==. (13271 bytes)
11509 verbose exit [ 1, true ]
```

### Steps to reproduce the problem

Follow the instuction how to build and install cate-desktop

### Specifications 

Windows 10 Anniversary Update
Node x64 v8.6.0

**Comment by forman** [comment]
Please use Node LTS version. Updated README accordingly.
