### ISSUE TITLE
Error - Removal of Resource Causes Failure Instead of Gracefully Informing User.

### ISSUE THREAD

**Issue by esacci** [CCI-Tools/cate#589]
Mac dev7.

To recreate - (1) click on resource which itself has a resource dependent, (2) click "-", (3) click 'yes' I'm sure I want to delete the resource. 

<img width="1528" alt="screen shot 2018-03-23 at 15 55 02" src="https://user-images.githubusercontent.com/29626821/37839688-f6bc3150-2eb2-11e8-8357-535844aa9ea0.png">

<img width="1021" alt="screen shot 2018-03-23 at 15 57 10" src="https://user-images.githubusercontent.com/29626821/37839693-fa8df638-2eb2-11e8-83cb-7f49445996dc.png">

<img width="1530" alt="screen shot 2018-03-23 at 15 55 32" src="https://user-images.githubusercontent.com/29626821/37839696-fdda20fa-2eb2-11e8-9cab-34a6f2819762.png">

Cate Desktop, version 2.0.0-dev.7

delete_workspace_resource() call raised exception: "Cannot delete resource "ds_1" because the following resource(s) depend on it: res_2"

An error (code 20) occurred in Cate Core:

Traceback (most recent call last):
  File "/Users/edpechorro/cate-2.0.0.dev7/lib/python3.6/site-packages/cate/util/web/jsonrpchandler.py", line 192, in send_service_method_result
    result = future.result()
  File "/Users/edpechorro/cate-2.0.0.dev7/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/Users/edpechorro/cate-2.0.0.dev7/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Users/edpechorro/cate-2.0.0.dev7/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/edpechorro/cate-2.0.0.dev7/lib/python3.6/site-packages/cate/util/web/jsonrpchandler.py", line 275, in call_service_method
    result = method(*method_params)
  File "/Users/edpechorro/cate-2.0.0.dev7/lib/python3.6/site-packages/cate/webapi/websocket.py", line 269, in delete_workspace_resource
    workspace = self.workspace_manager.delete_workspace_resource(base_dir, res_name)
  File "/Users/edpechorro/cate-2.0.0.dev7/lib/python3.6/site-packages/cate/core/wsmanag.py", line 333, in delete_workspace_resource
    workspace.delete_resource(res_name)
  File "/Users/edpechorro/cate-2.0.0.dev7/lib/python3.6/site-packages/cate/core/workspace.py", line 435, in delete_resource
    'depend on it: %s' % (res_name, ', '.join(dependent_steps)))
cate.core.workspace.WorkspaceError: Cannot delete resource "ds_1" because the following resource(s) depend on it: res_2

**Comment by forman** [comment]
Should be addressed when fixing #393

**Comment by forman** [comment]
Closed with #593
