### ISSUE TITLE
open workspace error

### ISSUE THREAD

**Issue by Evadzi** [CCI-Tools/cate#594]
When starting the  cate 2, I get the below workspace error message.

Cate Desktop, version 2.0.0-dev.8

open_workspace() call raised exception: "Not a valid workspace: C:\ESA_data"

An error (code 20) occurred in Cate Core:

Traceback (most recent call last):
  File "C:\Users\PIKE\cate-2.0.0.dev8\lib\site-packages\cate\util\web\jsonrpchandler.py", line 192, in send_service_method_result
    result = future.result()
  File "C:\Users\PIKE\cate-2.0.0.dev8\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "C:\Users\PIKE\cate-2.0.0.dev8\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\PIKE\cate-2.0.0.dev8\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\PIKE\cate-2.0.0.dev8\lib\site-packages\cate\util\web\jsonrpchandler.py", line 268, in call_service_method
    result = method(*method_params, monitor=monitor)
  File "C:\Users\PIKE\cate-2.0.0.dev8\lib\site-packages\cate\webapi\websocket.py", line 234, in open_workspace
    workspace = self.workspace_manager.open_workspace(base_dir, monitor=monitor)
  File "C:\Users\PIKE\cate-2.0.0.dev8\lib\site-packages\cate\core\wsmanag.py", line 194, in open_workspace
    workspace = Workspace.open(base_dir, monitor=monitor.child(50))
  File "C:\Users\PIKE\cate-2.0.0.dev8\lib\site-packages\cate\core\workspace.py", line 169, in open
    raise WorkspaceError('Not a valid workspace: %s' % base_dir)
cate.core.workspace.WorkspaceError: Not a valid workspace: C:\ESA_data
Cate Desktop, version 2.0.0-dev.8

open_workspace() call raised exception: "Not a valid workspace: C:\ESA_data"

An error (code 20) occurred in Cate Core:

Traceback (most recent call last):
  File "C:\Users\PIKE\cate-2.0.0.dev8\lib\site-packages\cate\util\web\jsonrpchandler.py", line 192, in send_service_method_result
    result = future.result()
  File "C:\Users\PIKE\cate-2.0.0.dev8\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "C:\Users\PIKE\cate-2.0.0.dev8\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\PIKE\cate-2.0.0.dev8\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\PIKE\cate-2.0.0.dev8\lib\site-packages\cate\util\web\jsonrpchandler.py", line 268, in call_service_method
    result = method(*method_params, monitor=monitor)
  File "C:\Users\PIKE\cate-2.0.0.dev8\lib\site-packages\cate\webapi\websocket.py", line 234, in open_workspace
    workspace = self.workspace_manager.open_workspace(base_dir, monitor=monitor)
  File "C:\Users\PIKE\cate-2.0.0.dev8\lib\site-packages\cate\core\wsmanag.py", line 194, in open_workspace
    workspace = Workspace.open(base_dir, monitor=monitor.child(50))
  File "C:\Users\PIKE\cate-2.0.0.dev8\lib\site-packages\cate\core\workspace.py", line 169, in open
    raise WorkspaceError('Not a valid workspace: %s' % base_dir)
cate.core.workspace.WorkspaceError: Not a valid workspace: C:\ESA_data

**Comment by forman** [comment]
Could you please attach your `~/.cate/preferences.json` file.

**Comment by Evadzi** [comment]
Thanks!
