### ISSUE TITLE
Operation Errors for Read_geo_date_frame

### ISSUE THREAD

**Issue by aghenry** [CCI-Tools/cate#649]
**Please read this carefully before submitting a new issue:**

1. Make sure the issue you are about to report has not been reported before! 
2. If you are allowed to assign labels, please 
   * Use label "support_request" if you have a question
   * Use label "help_wanted" if you are a Cate developer and you have an issue that falls 
     completely in your scope of activity, but with which you are stuck with and need help with. 
   * Use label "discussion" for an issue that doesn't warrant code changes right away, 
     but is rather meant as a place for discussion on how to solve a particular problem. 
3. The following template should be used for reporting bugs, inconsistencies, and feature requests.
   Note that you can use hashtag followed by issue number to refer to other issues (e.g. #234) and 
   use the add character followed by a GitHub user name (e.g. @forman) to refer to other users.   

### Expected behavior

Import KMZ File created on google earth

### Actual behavior

Operation Error because " unsupported driver: LIBKMZ" 
Job: Executing operation "read_geo_data_frame"
Message: unsupported driver: 'LIBKML'
Code: -32003
Method: set_workspace_resource
Exception: fiona.errors.DriverError

Traceback (most recent call last):
  File "/Users/agathehenry/.local/lib/python3.6/site-packages/cate-2.0.0.dev10-py3.6.egg/cate/util/web/jsonrpchandler.py", line 209, in send_service_method_result
    result = future.result()
  File "/Users/agathehenry/Downloads/cate-1.0.0/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/Users/agathehenry/Downloads/cate-1.0.0/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Users/agathehenry/Downloads/cate-1.0.0/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/agathehenry/.local/lib/python3.6/site-packages/cate-2.0.0.dev10-py3.6.egg/cate/util/web/jsonrpchandler.py", line 306, in call_service_method
    result = method(*method_params, monitor=monitor)
  File "/Users/agathehenry/.local/lib/python3.6/site-packages/cate-2.0.0.dev10-py3.6.egg/cate/webapi/websocket.py", line 289, in set_workspace_resource
    monitor=monitor)
  File "/Users/agathehenry/.local/lib/python3.6/site-packages/cate-2.0.0.dev10-py3.6.egg/cate/core/wsmanag.py", line 317, in set_workspace_resource
    workspace.execute_workflow(res_name=res_name, monitor=monitor)
  File "/Users/agathehenry/.local/lib/python3.6/site-packages/cate-2.0.0.dev10-py3.6.egg/cate/core/workspace.py", line 605, in execute_workflow
    self.workflow.invoke_steps(steps, context=self._new_context(), monitor=monitor)
  File "/Users/agathehenry/.local/lib/python3.6/site-packages/cate-2.0.0.dev10-py3.6.egg/cate/core/workflow.py", line 627, in invoke_steps
    steps[0].invoke(context=context, monitor=monitor)
  File "/Users/agathehenry/.local/lib/python3.6/site-packages/cate-2.0.0.dev10-py3.6.egg/cate/core/workflow.py", line 318, in invoke
    self._invoke_impl(_new_context(context, step=self), monitor=monitor)
  File "/Users/agathehenry/.local/lib/python3.6/site-packages/cate-2.0.0.dev10-py3.6.egg/cate/core/workflow.py", line 980, in _invoke_impl
    return_value = self._op(monitor=monitor, **input_values)
  File "/Users/agathehenry/.local/lib/python3.6/site-packages/cate-2.0.0.dev10-py3.6.egg/cate/core/op.py", line 216, in __call__
    return_value = self._wrapped_op(**input_values)
  File "/Users/agathehenry/.local/lib/python3.6/site-packages/cate-2.0.0.dev10-py3.6.egg/cate/ops/io.py", line 301, in read_geo_data_frame
    features = fiona.open(file, mode="r", crs=crs, **kwargs)
  File "/Users/agathehenry/Downloads/cate-1.0.0/envs/cate-env/lib/python3.6/site-packages/fiona/__init__.py", line 165, in open
    enabled_drivers=enabled_drivers)
  File "/Users/agathehenry/Downloads/cate-1.0.0/envs/cate-env/lib/python3.6/site-packages/fiona/collection.py", line 162, in __init__
    self.guard_driver_mode()
  File "/Users/agathehenry/Downloads/cate-1.0.0/envs/cate-env/lib/python3.6/site-packages/fiona/collection.py", line 176, in guard_driver_mode
    raise DriverError("unsupported driver: %r" % driver)
fiona.errors.DriverError: unsupported driver: 'LIBKML'

### Steps to reproduce the problem

1. Select in the operations panel "Read_geo_data_frame"
2. Link the kHz file address in the first bar
3. Let ces and 'more_args' empty
4. Add step

Thanks, 
Agathe

**Comment by forman** [comment]
Note, this is not a bug because KMZ/KML is currently not among the supported formats. Consider converting it to GeoJSON or ESRI Shapefile format, then try again.

@papesci see [here](https://gis.stackexchange.com/questions/114066/handling-kml-csv-with-geopandas-drivererror-unsupported-driver-ucsv?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa), we may give it a try

**Comment by esacci** [comment]
I suggest the Operations panel clarifies this by avoiding the phrase "formats such as" in the sentence "Reads geo-data from files with formats such as ESRI Shapefile, GeoJSON, GML" ; this implies ESRI Shapefile, GeoJSON, GML are examples rather than the actual list.

<img width="495" alt="screen shot 2018-05-15 at 11 54 08" src="https://user-images.githubusercontent.com/29626821/40052883-1f1bfcb8-5837-11e8-96ee-e230c1052024.png">
