### ISSUE TITLE
cate-desktop unsupported driver GML 

### ISSUE THREAD

**Issue by dzelge** [CCI-Tools/cate#734]
__Expected behaviour__:

Allow or don't allow GML data format when using the read_geo_dataframe operation

__Actual behaviour__:

When chosing GML as input data format I get the follwing error:

```
Traceback (most recent call last):
  File "C:\Users\Helge\AppData\Local\conda\conda\envs\cate-env\lib\site-packages\cate-2.0.0.dev17-py3.6.egg\cate\util\web\jsonrpchandler.py", line 209, in send_service_method_result
    result = future.result()
  File "C:\Users\Helge\AppData\Local\conda\conda\envs\cate-env\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "C:\Users\Helge\AppData\Local\conda\conda\envs\cate-env\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\Helge\AppData\Local\conda\conda\envs\cate-env\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Helge\AppData\Local\conda\conda\envs\cate-env\lib\site-packages\cate-2.0.0.dev17-py3.6.egg\cate\util\web\jsonrpchandler.py", line 306, in call_service_method
    result = method(*method_params, monitor=monitor)
  File "C:\Users\Helge\AppData\Local\conda\conda\envs\cate-env\lib\site-packages\cate-2.0.0.dev17-py3.6.egg\cate\webapi\websocket.py", line 291, in set_workspace_resource
    monitor=monitor)
  File "C:\Users\Helge\AppData\Local\conda\conda\envs\cate-env\lib\site-packages\cate-2.0.0.dev17-py3.6.egg\cate\core\wsmanag.py", line 317, in set_workspace_resource
    workspace.execute_workflow(res_name=res_name, monitor=monitor)
  File "C:\Users\Helge\AppData\Local\conda\conda\envs\cate-env\lib\site-packages\cate-2.0.0.dev17-py3.6.egg\cate\core\workspace.py", line 633, in execute_workflow
    self.workflow.invoke_steps(steps, context=self._new_context(), monitor=monitor)
  File "C:\Users\Helge\AppData\Local\conda\conda\envs\cate-env\lib\site-packages\cate-2.0.0.dev17-py3.6.egg\cate\core\workflow.py", line 627, in invoke_steps
    steps[0].invoke(context=context, monitor=monitor)
  File "C:\Users\Helge\AppData\Local\conda\conda\envs\cate-env\lib\site-packages\cate-2.0.0.dev17-py3.6.egg\cate\core\workflow.py", line 318, in invoke
    self._invoke_impl(_new_context(context, step=self), monitor=monitor)
  File "C:\Users\Helge\AppData\Local\conda\conda\envs\cate-env\lib\site-packages\cate-2.0.0.dev17-py3.6.egg\cate\core\workflow.py", line 980, in _invoke_impl
    return_value = self._op(monitor=monitor, **input_values)
  File "C:\Users\Helge\AppData\Local\conda\conda\envs\cate-env\lib\site-packages\cate-2.0.0.dev17-py3.6.egg\cate\core\op.py", line 216, in __call__
    return_value = self._wrapped_op(**input_values)
  File "C:\Users\Helge\AppData\Local\conda\conda\envs\cate-env\lib\site-packages\cate-2.0.0.dev17-py3.6.egg\cate\ops\io.py", line 431, in read_geo_data_frame
    features = fiona.open(file, mode="r", crs=crs, **kwargs)
  File "C:\Users\Helge\AppData\Local\conda\conda\envs\cate-env\lib\site-packages\fiona\__init__.py", line 165, in open
    enabled_drivers=enabled_drivers)
  File "C:\Users\Helge\AppData\Local\conda\conda\envs\cate-env\lib\site-packages\fiona\collection.py", line 162, in __init__
    self.guard_driver_mode()
  File "C:\Users\Helge\AppData\Local\conda\conda\envs\cate-env\lib\site-packages\fiona\collection.py", line 176, in guard_driver_mode
    raise DriverError("unsupported driver: %r" % driver)
fiona.errors.DriverError: unsupported driver: 'GML'
```

__Steps__:
- Click read_geo_dataframe operation
- Click 'add step'
- Chose GML data format
- Click open

__Version__

Cate desktop Version 2.0.0-dev.17

**Comment by forman** [comment]
@dzelge This is a known problem. Could you please remove "GML" from the possible value set.
We might add "GML" later or by plugin.

**Comment by forman** [comment]
@dzelge Please close!
