### ISSUE TITLE
Some data frame operations fail unexpectedly with Glaciers CCI Shapefiles

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate#751]
### Expected behavior

All  data frame operations should work Glaciers CCI Shapefiles in the same way. Note that we have numerous green unit-level tests for these operations.

### Actual behavior

Some data frame operations fail unexpectedly and constantly with a `GeoDataFrame` read from Glaciers CCI Shapefiles. Sometimes also for GeoJSON sources, for example `data_frame_find_closest()` fails for a `GeoDataFrame` read from file `cate/ds/data/countries/countries.geojson`.

* `data_frame_subset()` when given a polygonal region will find 0 rows even if Glacier polygons are fully contained
* `data_frame_query()` when given a polygonal region in query expression (e.gf. `@within("POLYGON ((...))")'`) will find 0 rows even if Glacier polygons are fully contained
* `data_frame_find_closest()` when given a point close to a Glacier polygon will find 0 rows

### Steps to reproduce the problem

For example:

1. gdf_1 = `read_geo_data_frame("my/path/to/a/glaciers.shp")`
2. df_1 = `data_frame_query(df=gdf_1, query="@within('POLYGON ((...))')")`

### Specifications 

Cate 2.0.0-dev.18

**Comment by forman** [comment]
Hint: a `GeoDataFrame` ingested by `read_geo_data_frame()` in an instance of `cate.core.types.GeoDataFrame` which **is not** an instance of `geopandas.GeoDataFrame`. Instead it serves as a proxy for the geopandas instance (which is lazily created) and should behave exactly as one.

**Comment by forman** [comment]
@dzelge just tested `data_frame_subset()` with a BBOX rectangle as `region` and glaciers CCI. It failed immediately:

```
Traceback (most recent call last):
  File "D:\Projects\PycharmProjects\cate\cate\util\web\jsonrpchandler.py", line 209, in send_service_method_result
    result = future.result()
  File "D:\Miniconda3\envs\cate-env\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "D:\Miniconda3\envs\cate-env\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "D:\Miniconda3\envs\cate-env\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Projects\PycharmProjects\cate\cate\util\web\jsonrpchandler.py", line 306, in call_service_method
    result = method(*method_params, monitor=monitor)
  File "D:\Projects\PycharmProjects\cate\cate\webapi\websocket.py", line 292, in set_workspace_resource
    monitor=monitor)
  File "D:\Projects\PycharmProjects\cate\cate\core\wsmanag.py", line 317, in set_workspace_resource
    workspace.execute_workflow(res_name=res_name, monitor=monitor)
  File "D:\Projects\PycharmProjects\cate\cate\core\workspace.py", line 660, in execute_workflow
    self.workflow.invoke_steps(steps, context=self._new_context(), monitor=monitor)
  File "D:\Projects\PycharmProjects\cate\cate\core\workflow.py", line 632, in invoke_steps
    step.invoke(context=context, monitor=monitor.child(work=1))
  File "D:\Projects\PycharmProjects\cate\cate\core\workflow.py", line 318, in invoke
    self._invoke_impl(_new_context(context, step=self), monitor=monitor)
  File "D:\Projects\PycharmProjects\cate\cate\core\workflow.py", line 980, in _invoke_impl
    return_value = self._op(monitor=monitor, **input_values)
  File "D:\Projects\PycharmProjects\cate\cate\core\op.py", line 216, in __call__
    return_value = self._wrapped_op(**input_values)
  File "D:\Projects\PycharmProjects\cate\cate\ops\data_frame.py", line 208, in data_frame_subset
    gdf = data_frame_query(gdf, f'@{geom_op}("{geom_str}")')
  File "D:\Projects\PycharmProjects\cate\cate\core\op.py", line 216, in __call__
    return_value = self._wrapped_op(**input_values)
  File "D:\Projects\PycharmProjects\cate\cate\ops\data_frame.py", line 159, in data_frame_query
    global_dict={})
  File "D:\Miniconda3\envs\cate-env\lib\site-packages\pandas\core\frame.py", line 2847, in query
    res = self.eval(expr, **kwargs)
  File "D:\Miniconda3\envs\cate-env\lib\site-packages\pandas\core\frame.py", line 2962, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "D:\Miniconda3\envs\cate-env\lib\site-packages\pandas\core\computation\eval.py", line 291, in eval
    truediv=truediv)
  File "D:\Miniconda3\envs\cate-env\lib\site-packages\pandas\core\computation\expr.py", line 739, in __init__
    self.terms = self.parse()
  File "D:\Miniconda3\envs\cate-env\lib\site-packages\pandas\core\computation\expr.py", line 756, in parse
    return self._visitor.visit(self.expr)
  File "D:\Miniconda3\envs\cate-env\lib\site-packages\pandas\core\computation\expr.py", line 321, in visit
    return visitor(node, **kwargs)
  File "D:\Miniconda3\envs\cate-env\lib\site-packages\pandas\core\computation\expr.py", line 327, in visit_Module
    return self.visit(expr, **kwargs)
  File "D:\Miniconda3\envs\cate-env\lib\site-packages\pandas\core\computation\expr.py", line 321, in visit
    return visitor(node, **kwargs)
  File "D:\Miniconda3\envs\cate-env\lib\site-packages\pandas\core\computation\expr.py", line 330, in visit_Expr
    return self.visit(node.value, **kwargs)
  File "D:\Miniconda3\envs\cate-env\lib\site-packages\pandas\core\computation\expr.py", line 321, in visit
    return visitor(node, **kwargs)
  File "D:\Miniconda3\envs\cate-env\lib\site-packages\pandas\core\computation\expr.py", line 591, in visit_Call_35
    return self.const_type(res(*new_args, **kwargs), self.env)
  File "D:\Projects\PycharmProjects\cate\cate\ops\data_frame.py", line 145, in _within
    return _data_frame_geometry_op(data_frame.geometry.within, geometry, crs)
  File "D:\Projects\PycharmProjects\cate\cate\ops\data_frame.py", line 442, in _data_frame_geometry_op
    geometry = _transform_coordinates(geometry, crs)
  File "D:\Projects\PycharmProjects\cate\cate\ops\data_frame.py", line 426, in _transform_coordinates
    raise ValidationError('No crs in GeoDataFrame' + str(crs))
cate.core.types.ValidationError: No crs in GeoDataFrame{'proj': 'laea', 'lat_0': 90, 'lon_0': -43, 'x_0': 0, 'y_0': 0, 'datum': 'WGS84', 'units': 'm', 'no_defs': True}
```

**Comment by forman** [comment]
We should include a unit-test covering the case where crs=`{'proj': 'laea', 'lat_0': 90, 'lon_0': -43, 'x_0': 0, 'y_0': 0, 'datum': 'WGS84', 'units': 'm', 'no_defs': True}`

**Comment by forman** [comment]
After fixing the above, I now get strange behaviour when serializing GeoDataFrame resources for the GUI. First it seems that 1-element `geom_type` Series cannot be indexed by integers (0):

```
Traceback (most recent call last):
  File "D:\Projects\PycharmProjects\cate\cate\util\web\jsonrpchandler.py", line 209, in send_service_method_result
    result = future.result()
  File "D:\Miniconda3\envs\cate-env\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "D:\Miniconda3\envs\cate-env\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "D:\Miniconda3\envs\cate-env\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Projects\PycharmProjects\cate\cate\util\web\jsonrpchandler.py", line 306, in call_service_method
    result = method(*method_params, monitor=monitor)
  File "D:\Projects\PycharmProjects\cate\cate\webapi\websocket.py", line 293, in set_workspace_resource
    return [workspace.to_json_dict(), res_name]
  File "D:\Projects\PycharmProjects\cate\cate\core\workspace.py", line 281, in to_json_dict
    ('resources', self._resources_to_json_list())
  File "D:\Projects\PycharmProjects\cate\cate\core\workspace.py", line 293, in _resources_to_json_list
    resource_descriptor = self._get_resource_descriptor(res_id, res_update_count, res_name, resource)
  File "D:\Projects\PycharmProjects\cate\cate\core\workspace.py", line 313, in _get_resource_descriptor
    cls._update_resource_json_from_data_frame(resource_json, resource)
  File "D:\Projects\PycharmProjects\cate\cate\core\workspace.py", line 363, in _update_resource_json_from_data_frame
    attributes['geom_type'] = str(data_frame.geom_type[0])
  File "D:\Miniconda3\envs\cate-env\lib\site-packages\pandas\core\series.py", line 767, in __getitem__
    result = self.index.get_value(self, key)
  File "D:\Miniconda3\envs\cate-env\lib\site-packages\pandas\core\indexes\base.py", line 3118, in get_value
    tz=getattr(series.dtype, 'tz', None))
  File "pandas/_libs/index.pyx", line 106, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 114, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 958, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 964, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 0
```

After fixing this, the same happens for N-element `geometry` Series, that cannot be indexed by integers (using key 0):

```
Traceback (most recent call last):
  File "D:\Projects\PycharmProjects\cate\cate\util\web\jsonrpchandler.py", line 209, in send_service_method_result
    result = future.result()
  File "D:\Miniconda3\envs\cate-env\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "D:\Miniconda3\envs\cate-env\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "D:\Miniconda3\envs\cate-env\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Projects\PycharmProjects\cate\cate\util\web\jsonrpchandler.py", line 306, in call_service_method
    result = method(*method_params, monitor=monitor)
  File "D:\Projects\PycharmProjects\cate\cate\webapi\websocket.py", line 292, in set_workspace_resource
    monitor=monitor)
  File "D:\Projects\PycharmProjects\cate\cate\core\wsmanag.py", line 317, in set_workspace_resource
    workspace.execute_workflow(res_name=res_name, monitor=monitor)
  File "D:\Projects\PycharmProjects\cate\cate\core\workspace.py", line 663, in execute_workflow
    self.workflow.invoke_steps(steps, context=self._new_context(), monitor=monitor)
  File "D:\Projects\PycharmProjects\cate\cate\core\workflow.py", line 632, in invoke_steps
    step.invoke(context=context, monitor=monitor.child(work=1))
  File "D:\Projects\PycharmProjects\cate\cate\core\workflow.py", line 318, in invoke
    self._invoke_impl(_new_context(context, step=self), monitor=monitor)
  File "D:\Projects\PycharmProjects\cate\cate\core\workflow.py", line 980, in _invoke_impl
    return_value = self._op(monitor=monitor, **input_values)
  File "D:\Projects\PycharmProjects\cate\cate\core\op.py", line 216, in __call__
    return_value = self._wrapped_op(**input_values)
  File "D:\Projects\PycharmProjects\cate\cate\ops\data_frame.py", line 270, in data_frame_find_closest
    geometry = geometries[i]
  File "D:\Miniconda3\envs\cate-env\lib\site-packages\geopandas\geoseries.py", line 139, in __getitem__
    return self._wrapped_pandas_method('__getitem__', key)
  File "D:\Miniconda3\envs\cate-env\lib\site-packages\geopandas\geoseries.py", line 131, in _wrapped_pandas_method
    val = getattr(super(GeoSeries, self), mtd)(*args, **kwargs)
  File "D:\Miniconda3\envs\cate-env\lib\site-packages\pandas\core\series.py", line 767, in __getitem__
    result = self.index.get_value(self, key)
  File "D:\Miniconda3\envs\cate-env\lib\site-packages\pandas\core\indexes\base.py", line 3118, in get_value
    tz=getattr(series.dtype, 'tz', None))
  File "pandas/_libs/index.pyx", line 106, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 114, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 958, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 964, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 0
```

**Comment by forman** [comment]
Ok, it seems that `Series.iloc()` must be used for consistent indexing. While 

    gdf.geometry[0]

will work on geometry column for a Shapefile ingested using `gpd.read_file("my/shape.shp")`, it will raise `KeyError: 0` when applied to a GeoDataFrame which is a *view* on onother GeoDataFrame.
