### ISSUE TITLE
Error on opening saved workspace for use case 22 happy path

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#772]
### Expected behavior
@forman 
Opened new workspace called UC22, executed use case 22 happy path using GUI, saved and closed workspace.
Then selected File->Open Workspace then folder UC22
Expected workspace to open

### Actual behavior

Shortly after starting to load the workspace, an error was seen

![uc22](https://user-images.githubusercontent.com/29569434/46071860-7ea46100-c170-11e8-9e58-a5074f628a7f.PNG)

Traceback (most recent call last):
  File "C:\Users\HClifton\cate-2.0.0.dev19\lib\site-packages\cate\ops\arithmetics.py", line 324, in _exec_script
    safe_exec(script, local_namespace=local_namespace)
  File "C:\Users\HClifton\cate-2.0.0.dev19\lib\site-packages\cate\util\safe.py", line 140, in safe_exec
    return exec(source_code, get_safe_globals(), local_namespace or {})
  File "<string>", line 1, in <module>
TypeError: 'NoneType' object is not subscriptable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\HClifton\cate-2.0.0.dev19\lib\site-packages\cate\util\web\jsonrpchandler.py", line 209, in send_service_method_result
    result = future.result()
  File "C:\Users\HClifton\cate-2.0.0.dev19\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "C:\Users\HClifton\cate-2.0.0.dev19\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\HClifton\cate-2.0.0.dev19\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\HClifton\cate-2.0.0.dev19\lib\site-packages\cate\util\web\jsonrpchandler.py", line 306, in call_service_method
    result = method(*method_params, monitor=monitor)
  File "C:\Users\HClifton\cate-2.0.0.dev19\lib\site-packages\cate\webapi\websocket.py", line 241, in open_workspace
    workspace = self.workspace_manager.open_workspace(base_dir, monitor=monitor)
  File "C:\Users\HClifton\cate-2.0.0.dev19\lib\site-packages\cate\core\wsmanag.py", line 200, in open_workspace
    workspace.execute_workflow(monitor=monitor.child(50))
  File "C:\Users\HClifton\cate-2.0.0.dev19\lib\site-packages\cate\core\workspace.py", line 662, in execute_workflow
    self.workflow.invoke_steps(steps, context=self._new_context(), monitor=monitor)
  File "C:\Users\HClifton\cate-2.0.0.dev19\lib\site-packages\cate\core\workflow.py", line 632, in invoke_steps
    step.invoke(context=context, monitor=monitor.child(work=1))
  File "C:\Users\HClifton\cate-2.0.0.dev19\lib\site-packages\cate\core\workflow.py", line 318, in invoke
    self._invoke_impl(_new_context(context, step=self), monitor=monitor)
  File "C:\Users\HClifton\cate-2.0.0.dev19\lib\site-packages\cate\core\workflow.py", line 980, in _invoke_impl
    return_value = self._op(monitor=monitor, **input_values)
  File "C:\Users\HClifton\cate-2.0.0.dev19\lib\site-packages\cate\core\op.py", line 216, in __call__
    return_value = self._wrapped_op(**input_values)
  File "C:\Users\HClifton\cate-2.0.0.dev19\lib\site-packages\cate\ops\arithmetics.py", line 276, in compute_dataset
    data_vars = _exec_script(script, (xr.DataArray, np.ndarray, float, int), _ctx, ds, monitor)
  File "C:\Users\HClifton\cate-2.0.0.dev19\lib\site-packages\cate\ops\arithmetics.py", line 326, in _exec_script
    raise ValidationError(f'Error in Python script: {e}') from e
cate.core.types.ValidationError: Error in Python script: 'NoneType' object is not subscriptable

### Steps to reproduce the problem

See above
Other saved workspaces for use case happy paths do open successfully

### Specifications 

cate-2.0.0-dev.19
Windows 7 Professional

**Comment by forman** [comment]
@HelenClifton A possible scenario for that is, that the data source is not available anymore, so `open_dataset` operation may have returned `None`,  (actually it should never return `None`).

Please provide link here to happy path for UC22.

**Comment by HelenClifton** [comment]
@forman Here it is 
[uc22 happy path.docx](https://github.com/CCI-Tools/cate/files/2419375/uc22.happy.path.docx)
