### ISSUE TITLE
Error on opening saved workspace for use case 4 happy path

### ISSUE THREAD

**Issue by HelenClifton** [CCI-Tools/cate#773]
### Expected behavior

@forman Opened new workspace called UC04, executed use case 4 happy path using GUI, saved and closed workspace.
Then selected File->Open Workspace then folder UC04
Expected workspace to open

### Actual behaviour

During the loading of the workspace, an error with file permissions was seen

![uc04](https://user-images.githubusercontent.com/29569434/46074303-ae566780-c176-11e8-9780-34c312f43ef9.PNG)

Traceback (most recent call last):
  File "C:\Users\HClifton\cate-2.0.0.dev19\lib\site-packages\cate\util\web\jsonrpchandler.py", line 209, in send_service_method_result
    result = future.result()
  File "C:\Users\HClifton\cate-2.0.0.dev19\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "C:\Users\HClifton\cate-2.0.0.dev19\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\HClifton\cate-2.0.0.dev19\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\HClifton\cate-2.0.0.dev19\lib\site-packages\cate\util\web\jsonrpchandler.py", line 306, in call_service_method
    result = method(*method_params, monitor=monitor)
  File "C:\Users\HClifton\cate-2.0.0.dev19\lib\site-packages\cate\webapi\websocket.py", line 241, in open_workspace
    workspace = self.workspace_manager.open_workspace(base_dir, monitor=monitor)
  File "C:\Users\HClifton\cate-2.0.0.dev19\lib\site-packages\cate\core\wsmanag.py", line 200, in open_workspace
    workspace.execute_workflow(monitor=monitor.child(50))
  File "C:\Users\HClifton\cate-2.0.0.dev19\lib\site-packages\cate\core\workspace.py", line 662, in execute_workflow
    self.workflow.invoke_steps(steps, context=self._new_context(), monitor=monitor)
  File "C:\Users\HClifton\cate-2.0.0.dev19\lib\site-packages\cate\core\workflow.py", line 632, in invoke_steps
    step.invoke(context=context, monitor=monitor.child(work=1))
  File "C:\Users\HClifton\cate-2.0.0.dev19\lib\site-packages\cate\core\workflow.py", line 318, in invoke
    self._invoke_impl(_new_context(context, step=self), monitor=monitor)
  File "C:\Users\HClifton\cate-2.0.0.dev19\lib\site-packages\cate\core\workflow.py", line 980, in _invoke_impl
    return_value = self._op(monitor=monitor, **input_values)
  File "C:\Users\HClifton\cate-2.0.0.dev19\lib\site-packages\cate\core\op.py", line 216, in __call__
    return_value = self._wrapped_op(**input_values)
  File "C:\Users\HClifton\cate-2.0.0.dev19\lib\site-packages\cate\ops\io.py", line 589, in write_netcdf4
    obj.to_netcdf(file, format='NETCDF4', engine=engine)
  File "C:\Users\HClifton\cate-2.0.0.dev19\lib\site-packages\xarray\core\dataset.py", line 1150, in to_netcdf
    compute=compute)
  File "C:\Users\HClifton\cate-2.0.0.dev19\lib\site-packages\xarray\backends\api.py", line 714, in to_netcdf
    autoclose=autoclose, lock=lock)
  File "C:\Users\HClifton\cate-2.0.0.dev19\lib\site-packages\xarray\backends\netCDF4_.py", line 332, in open
    ds = opener()
  File "C:\Users\HClifton\cate-2.0.0.dev19\lib\site-packages\xarray\backends\netCDF4_.py", line 231, in _open_netcdf4_group
    ds = nc4.Dataset(filename, mode=mode, **kwargs)
  File "netCDF4\_netCDF4.pyx", line 2111, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4\_netCDF4.pyx", line 1731, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'C:\\Users\\HClifton\\Desktop\\CCI toolbox\\WORKSPACE PARENT FOLDER\\UC04\\temp_lta.nc'

### Steps to reproduce the problem

See above
Other saved workspaces for use case happy paths do open successfully
(apart from uc22 see #772)

### Specifications 

cate-2.0.0-dev.19
Windows 7 Professional

**Comment by HelenClifton** [comment]
@forman happy path 
[uc04 happy path.docx](https://github.com/CCI-Tools/cate/files/2419377/uc04.happy.path.docx)

**Comment by forman** [comment]
@HelenClifton could you please test with dev20, it may have been related to #765.

**Comment by HelenClifton** [comment]
@forman Confirmed it still happens with the dev.20
