### ISSUE TITLE
[Failure] Failed to install 2.0.0-dev.20 as "Update"

### ISSUE THREAD

**Issue by esacci** [CCI-Tools/cate#776]
Failure to install 2.0.0-dev.20.

I have an existing (dev) version on my laptop.

<img width="598" alt="screen shot 2018-09-27 at 13 42 42" src="https://user-images.githubusercontent.com/29626821/46147142-92c58c80-c25c-11e8-9dde-bd9fc46bdc31.png">
<img width="592" alt="screen shot 2018-09-27 at 13 46 59" src="https://user-images.githubusercontent.com/29626821/46147145-95c07d00-c25c-11e8-84ab-3cdc50b2c16d.png">

**Comment by esacci** [comment]
log:

[2018-09-27 13:42:09.190] [info] ===============================================================================
[2018-09-27 13:42:09.194] [info] Cate Desktop, version 2.0.0-dev.20
[2018-09-27 13:42:09.194] [info] ===============================================================================
[2018-09-27 13:42:09.194] [info] process.versions = { http_parser: '2.7.0',
  node: '8.2.1',
  v8: '5.9.211.38',
  uv: '1.13.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  openssl: '1.0.2l',
  electron: '1.8.8',
  chrome: '59.0.3071.115',
  'atom-shell': '1.8.8' }
[2018-09-27 13:42:09.201] [info] User preferences successfully loaded from "/Users/<#>/.cate/preferences.json"
[2018-09-27 13:42:09.201] [warn] debugWorldView = false
[2018-09-27 13:42:09.202] [info] process.env.NODE_ENV = production
[2018-09-27 13:42:09.202] [info] appPath: /Applications/Cate Desktop.app/Contents/Resources/app.asar
[2018-09-27 13:42:09.202] [info] appConfig: { webAPIConfig:
   { servicePort: 9090,
     serviceAddress: '',
     serviceFile: '/Users/<#>/.cate/webapi-info.json',
     processOptions: {} } }
[2018-09-27 13:42:09.545] [info] Ready.
[2018-09-27 13:42:09.816] [info] Splash says: Waiting for Cate service...
[2018-09-27 13:42:09.816] [info] Waiting for response from Cate service http://localhost:9090/
[2018-09-27 13:42:09.827] [info] No response from Cate service after 0.01 seconds: Error: connect ECONNREFUSED 127.0.0.1:9090
[2018-09-27 13:42:09.828] [info] Splash says: Waiting for Cate service (0.01s)
[2018-09-27 13:42:09.830] [info] Checking Cate installation directory: /Users/<#>/.cate/2.0.0.dev11/cate.location
[2018-09-27 13:42:09.838] [info] Cate WebAPI executable found: /Users/<#>/anaconda3/envs/cate-env/bin/cate-webapi-start
[2018-09-27 13:42:09.841] [info] Computed setup information:  { oldCateDir: '/Users/<#>/anaconda3/envs/cate-env',
  newCateDir: '/Users/<#>/cate-2.0.0.dev20',
  oldCateVersion: '2.0.0.dev11',
  newCateVersion: '2.0.0.dev20',
  setupReason: 'UPDATE_CATE' }
[2018-09-27 13:42:09.842] [info] Cate directory set to /Users/<#>/anaconda3/envs/cate-env
[2018-09-27 13:42:47.459] [info] executing asynchronously:  source "/Users/<#>/anaconda3/envs/cate-env/bin/activate" "/Users/<#>/anaconda3/envs/cate-env"; exec cate --version { shell: '/bin/bash' }
[2018-09-27 13:42:50.889] [info] spawning asynchronously:  source "/Users/<#>/anaconda3/envs/cate-env/bin/activate" "/Users/<#>/anaconda3/envs/cate-env"; exec conda install --yes -c ccitools -c conda-forge conda cate-cli=2.0.0.dev20 undefined { shell: '/bin/bash' }
[2018-09-27 13:46:36.444] [info] executing asynchronously:  source "/Users/<#>/anaconda3/envs/cate-env/bin/activate" "/Users/<#>/anaconda3/envs/cate-env"; exec cate --version { shell: '/bin/bash' }
[2018-09-27 13:46:37.053] [error] Setup failed: Error: Installation of Python package cate 2.0.0.dev20 did not succeed.
    at spawnAsyncAndLog.then.then.ok (/Applications/Cate Desktop.app/Contents/Resources/app.asar/main/update-backend.js:163:23)
    at <anonymous>

**Comment by esacci** [comment]
Platform: MacOS Sierra v10.12.3

**Comment by forman** [comment]
@esacci Sorry for this.

Could you please to manually do what the update installer does by typing into in a terminal window:

    $ "/Users/<#>/anaconda3/envs/cate-env/bin/activate" "/Users/<#>/anaconda3/envs/cate-env"; exec cate --version

and kindly providing the output here?

Does `/Users/<#>/anaconda3/envs/cate-env/bin/activate` exist?

**Comment by forman** [comment]
see https://github.com/CCI-Tools/cate/issues/776#issuecomment-425091408

**Comment by esacci** [comment]
Hi, 

fyi - I've since tried to do an "Install a new Cate" with a similar failure, following a machine reboot.

I typed in the text as advised above and got the following:
MAC-EOP-2470:~ <#>$ "/Users/edpechorro/anaconda3/envs/cate-env/bin/activate" "/Users/edpechorro/anaconda3/envs/cate-env"; exec cate --version
-bash: /Users/edpechorro/anaconda3/envs/cate-env/bin/activate: Permission denied
-bash: exec: cate: not found

Yes, I notice /Users/<#>/anaconda3/envs/cate-env/bin/activate does exist:
-rw-rw-r--  1 <#> staff  141 27 Sep 13:46 activate

**Comment by esacci** [comment]
Should / could I try removing previous versions?

**Comment by esacci** [comment]
I attempted a clean install as follows, but it failed:

#1
MAC-EOP-2470:envs <#>$ ls -al
total 0
drwxr-xr-x   3 <#>  staff  102 11 May 09:04 .
drwxr-xr-x  24 <#>  staff  816 11 May 08:47 ..
drwxr-xr-x  21 <#>  staff  714 27 Sep 13:46 cate-env
MAC-EOP-2470:envs <#>$ pwd
/Users/<#>/anaconda3/envs
MAC-EOP-2470:envs <#>$ mv cate-env old-env
MAC-EOP-2470:envs <#>$ 

#2
MAC-EOP-2470:~ <#>$ cd .cate
MAC-EOP-2470:.cate <#>$ pwd
/Users/<#>/.cate
MAC-EOP-2470:.cate <#>$ cd ..
MAC-EOP-2470:~ <#>$ mv .cate .old
MAC-EOP-2470:~ <#>$ cd .cate
-bash: cd: .cate: No such file or directory
MAC-EOP-2470:~ <#>$ pwd
/Users/<#>
MAC-EOP-2470:~ <#>$ 

#3
MAC-EOP-2470:~ <#>$ mv cate oldcate
MAC-EOP-2470:~ <#>$ mv cate-2.0.0.dev20 oldcate-2.0.0.dev20
MAC-EOP-2470:~ <#>$ mv cate-desktop oldcate-desktop
MAC-EOP-2470:~ <#>$ pwd
/Users/<#>
MAC-EOP-2470:~ <#>$ 

#4
MAC-EOP-2470:~ <#>$ mv .cate .oldcate
MAC-EOP-2470:~ <#>$ pwd
/Users/<#>
MAC-EOP-2470:~ <#>$ cd 

#5 execute installer ("Automatic Setup")

#6 install fails.

<img width="594" alt="screen shot 2018-09-27 at 15 07 34" src="https://user-images.githubusercontent.com/29626821/46151904-bc37e580-c267-11e8-9eea-0ca2bdb68c3a.png">

MAC-EOP-2470:.cate <#>$ more cate-desktop.log 
[2018-09-27 14:55:14.471] [info] ===============================================================================
[2018-09-27 14:55:14.474] [info] Cate Desktop, version 2.0.0-dev.20
[2018-09-27 14:55:14.474] [info] ===============================================================================
[2018-09-27 14:55:14.474] [info] process.versions = { http_parser: '2.7.0',
  node: '8.2.1',
  v8: '5.9.211.38',
  uv: '1.13.1',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '57',
  openssl: '1.0.2l',
  electron: '1.8.8',
  chrome: '59.0.3071.115',
  'atom-shell': '1.8.8' }
[2018-09-27 14:55:14.476] [warn] debugWorldView = undefined
[2018-09-27 14:55:14.477] [info] process.env.NODE_ENV = production
[2018-09-27 14:55:14.477] [info] appPath: /Applications/Cate Desktop.app/Contents/Resources/app.asar
[2018-09-27 14:55:14.477] [info] appConfig: { webAPIConfig: 
   { servicePort: 9090,
     serviceAddress: '',
     serviceFile: '/Users/<#>/.cate/webapi-info.json',
     processOptions: {} } }
[2018-09-27 14:55:14.615] [info] Ready.
[2018-09-27 14:55:14.827] [info] Splash says: Waiting for Cate service...
[2018-09-27 14:55:14.828] [info] Waiting for response from Cate service http://localhost:9090/
[2018-09-27 14:55:14.838] [info] No response from Cate service after 0.01 seconds: Error: connect ECONNREFUSED 127.0.0.1:9090
[2018-09-27 14:55:14.838] [info] Splash says: Waiting for Cate service (0.01s)
[2018-09-27 14:55:14.839] [info] Computed setup information:  { newCateDir: '/Users/<#>/cate-2.0.0.dev20',
  newCateVersion: '2.0.0.dev20',
  setupReason: 'INSTALL_CATE' }
[2018-09-27 14:55:49.578] [info] executing asynchronously:  source "/Users/<#>/cate-2.0.0.dev20/bin/activate" "/Users/<#>/cate-2.0.0.dev20"; exec python --version { shell: '/bin/bash' }
[2018-09-27 14:55:49.624] [info] spawning asynchronously:  /var/folders/ms/9y7h200j13ddzq593z0z1gm00000gr/T/cate-vA5JMg/Miniconda3-4.5.4-MacOSX-x86_64.sh [ '-b', '-f', '-p', '/Users/<#>/cate-2.0.0.dev20' ] { shell: '/bin/bash' }
[2018-09-27 14:56:13.232] [info] executing asynchronously:  source "/Users/<#>/cate-2.0.0.dev20/bin/activate" "/Users/<#>/cate-2.0.0.dev20"; exec cate --version { shell: '/bin/bash' }
[2018-09-27 14:56:13.501] [warn] Retrieving Cate version failed (and this may be ok): Error: Command failed: source "/Users/<#>/cate-2.0.0.dev20/bin/activate" "/Users/<#>/cate-2.0.0.dev20"; exec cate --version
/bin/bash: line 0: exec: cate: not found
    at ChildProcess.exithandler (child_process.js:282:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
[2018-09-27 14:56:13.503] [info] spawning asynchronously:  source "/Users/<#>/cate-2.0.0.dev20/bin/activate" "/Users/<#>/cate-2.0.0.dev20"; exec conda install --yes -c ccitools -c conda-forge conda cate-cli=2.0.0.dev20 undefined { shell: '/bin/bash' }
[2018-09-27 15:06:16.983] [info] executing asynchronously:  source "/Users/<#>/cate-2.0.0.dev20/bin/activate" "/Users/<#>/cate-2.0.0.dev20"; exec cate --version { shell: '/bin/bash' }
[2018-09-27 15:06:17.436] [error] Setup failed: Error: Installation of Python package cate 2.0.0.dev20 did not succeed.
    at spawnAsyncAndLog.then.then.ok (/Applications/Cate Desktop.app/Contents/Resources/app.asar/main/update-backend.js:163:23)
    at <anonymous>

**Comment by esacci** [comment]
fyi - 


```
MAC-EOP-2470:~ <#>$ conda info --envs
# conda environments:
#
base                  *  /Users/<#>/anaconda3
old-env                  /Users/<#>/anaconda3/envs/old-env
                         /Users/<#>/cate-2.0.0.dev20
```

**Comment by forman** [comment]
@esacci we cannot reproduce it on our Mac. Updating and fresh installation, both work as expected. Do you have time for a Skype session?

**Comment by forman** [comment]
@esacci can you please try just the activation part:

> "/Users/<#>/anaconda3/envs/cate-env/bin/activate" "/Users/<#>/anaconda3/envs/cate-env"

**Comment by hans-permana** [comment]
The issue was there was a second (and older) cate installation was found in `~/.local` directory. This version of cate was somehow preferred to the newer one although the directory was not positioned as the first entry in the `$PATH`. After the removal of the second installation, Cate Desktop used always the right cate installation. We still need to investigate how cate is installed in `.local` directory.
