### ISSUE TITLE
Landcover: NetCDF access failure

### ISSUE THREAD

**Issue by Evadzi** [CCI-Tools/cate#783]
### Expected behavior

*I expect cate 2.0.0. dev-20 to successfully ingest landcover data from ODP*

### Actual behavior

*Opening data source failed because of NetCDF access failure*

### error message

 *Job: Opening data source "esacci.LC.5-yrs.L4.LCCS.multi-sensor.multi-platform.Map.1-6-1.r1"
Message: NetCDF: Access failure
Code: -32003
Method: set_workspace_resource
Exception: RuntimeError

Traceback (most recent call last):
 ``` File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\cate\util\web\jsonrpchandler.py", line 209, in send_service_method_result
    result = future.result()
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\cate\util\web\jsonrpchandler.py", line 306, in call_service_method
    result = method(*method_params, monitor=monitor)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\cate\webapi\websocket.py", line 292, in set_workspace_resource
    monitor=monitor)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\cate\core\wsmanag.py", line 320, in set_workspace_resource
    workspace.execute_workflow(res_name=res_name, monitor=monitor)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\cate\core\workspace.py", line 662, in execute_workflow
    self.workflow.invoke_steps(steps, context=self._new_context(), monitor=monitor)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\cate\core\workflow.py", line 627, in invoke_steps
    steps[0].invoke(context=context, monitor=monitor)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\cate\core\workflow.py", line 318, in invoke
    self._invoke_impl(_new_context(context, step=self), monitor=monitor)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\cate\core\workflow.py", line 980, in _invoke_impl
    return_value = self._op(monitor=monitor, **input_values)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\cate\core\op.py", line 216, in __call__
    return_value = self._wrapped_op(**input_values)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\cate\ops\io.py", line 83, in open_dataset
    monitor=monitor)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\cate\core\ds.py", line 588, in open_dataset
    monitor=monitor.child(80))
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\cate\ds\esa_cci_odp.py", line 1006, in make_local
    raise e
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\cate\ds\esa_cci_odp.py", line 999, in make_local
    self._make_local(local_ds, time_range, region, var_names, monitor=monitor)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\cate\ds\esa_cci_odp.py", line 884, in _make_local
    remote_dataset.to_netcdf(local_filepath)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\core\dataset.py", line 1150, in to_netcdf
    compute=compute)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\backends\api.py", line 723, in to_netcdf
    unlimited_dims=unlimited_dims, compute=compute)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\core\dataset.py", line 1075, in dump_to_store
    unlimited_dims=unlimited_dims)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\backends\common.py", line 362, in store
    variables, attributes = self.encode(variables, attributes)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\backends\common.py", line 447, in encode
    variables, attributes = cf_encoder(variables, attributes)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\conventions.py", line 573, in cf_encoder
    for k, v in iteritems(variables))
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\conventions.py", line 573, in <genexpr>
    for k, v in iteritems(variables))
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\conventions.py", line 235, in encode_cf_variable
    var = coder.encode(var, name=name)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\coding\times.py", line 384, in encode
    dims, data, attrs, encoding = unpack_for_encoding(variable)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\coding\variables.py", line 96, in unpack_for_encoding
    return var.dims, var.data, var.attrs.copy(), var.encoding.copy()
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\core\variable.py", line 295, in data
    return self.values
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\core\variable.py", line 387, in values
    return _as_array_or_item(self._data)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\core\variable.py", line 211, in _as_array_or_item
    data = np.asarray(data)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\numpy\core\numeric.py", line 501, in asarray
    return array(a, dtype, copy=False, order=order)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\core\indexing.py", line 624, in __array__
    self._ensure_cached()
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\core\indexing.py", line 621, in _ensure_cached
    self.array = NumpyIndexingAdapter(np.asarray(self.array))
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\numpy\core\numeric.py", line 501, in asarray
    return array(a, dtype, copy=False, order=order)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\core\indexing.py", line 602, in __array__
    return np.asarray(self.array, dtype=dtype)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\numpy\core\numeric.py", line 501, in asarray
    return array(a, dtype, copy=False, order=order)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\core\indexing.py", line 508, in __array__
    return np.asarray(array[self.key], dtype=None)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\coding\variables.py", line 66, in __getitem__
    return self.func(self.array[key])
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\coding\variables.py", line 66, in __getitem__
    return self.func(self.array[key])
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\numpy\core\numeric.py", line 501, in asarray
    return array(a, dtype, copy=False, order=order)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\core\indexing.py", line 508, in __array__
    return np.asarray(array[self.key], dtype=None)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\backends\netCDF4_.py", line 66, in __getitem__
    array = getitem(self.get_array(), key.tuple)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\backends\common.py", line 116, in robust_getitem
    return array[key]
  File "netCDF4\_netCDF4.pyx", line 4060, in netCDF4._netCDF4.Variable.__getitem__
  File "netCDF4\_netCDF4.pyx", line 4950, in netCDF4._netCDF4.Variable._get
  File "netCDF4\_netCDF4.pyx", line 1733, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: Access failure* ```


### Specifications 

*cate 2.0.0. dev-20, Windows 10*

**Comment by HelenClifton** [comment]
@forman @Evadzi As a note have just been able to successfully download this complete dataset with cate-2.0.0-dev.20 (was using Windows 7). 
Perhaps problem was a network glitch ?

**Comment by HelenClifton** [comment]
@Evadzi @forman As a note, have been able to successfully download this complete dataset using cate-2.0.0-dev.20 (Windows 7)
Maybe the problem seen was a network glitch ?

**Comment by papesci** [comment]
Hi Helen cn you please check it again with the fix https://github.com/CCI-Tools/cate/tree/798-pp-SST-copying-error merged in the master ?

**Comment by HelenClifton** [comment]
hi @papesci @forman @Evadzi As requested, I tested this dataset using the cate-2.0.0-dev.23 GUI (and Windows 7) and it downloaded and displayed with no problem.
@Evadzi are you still seeing the problem with cate-2.0.0-dev.23 ?

**Comment by Evadzi** [comment]
@HelenClifton ..Issue not resolved..
I tried again downloading from ODP using  the cate-2.0.0-dev.23 GUI and Windows 10

![image](https://user-images.githubusercontent.com/37798521/49137080-bb651380-f2eb-11e8-98b9-f08eb2d94aa4.png)

**It returns the same error as before:**

*Job: Opening data source "esacci.LC.5-yrs.L4.LCCS.multi-sensor.multi-platform.Map.1-6-1.r1"
Message: NetCDF: Access failure
Code: -32003
Method: set_workspace_resource
Exception: RuntimeError*

`Traceback (most recent call last):
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\util\web\jsonrpchandler.py", line 209, in send_service_method_result
    result = future.result()
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\util\web\jsonrpchandler.py", line 306, in call_service_method
    result = method(*method_params, monitor=monitor)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\webapi\websocket.py", line 292, in set_workspace_resource
    monitor=monitor)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\core\wsmanag.py", line 320, in set_workspace_resource
    workspace.execute_workflow(res_name=res_name, monitor=monitor)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\core\workspace.py", line 662, in execute_workflow
    self.workflow.invoke_steps(steps, context=self._new_context(), monitor=monitor)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\core\workflow.py", line 627, in invoke_steps
    steps[0].invoke(context=context, monitor=monitor)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\core\workflow.py", line 318, in invoke
    self._invoke_impl(_new_context(context, step=self), monitor=monitor)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\core\workflow.py", line 980, in _invoke_impl
    return_value = self._op(monitor=monitor, **input_values)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\core\op.py", line 216, in __call__
    return_value = self._wrapped_op(**input_values)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\ops\io.py", line 83, in open_dataset
    monitor=monitor)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\core\ds.py", line 588, in open_dataset
    monitor=monitor.child(80))
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\ds\esa_cci_odp.py", line 1010, in make_local
    raise e
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\ds\esa_cci_odp.py", line 1003, in make_local
    self._make_local(local_ds, time_range, region, var_names, monitor=monitor)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\ds\esa_cci_odp.py", line 874, in _make_local
    remote_dataset = adjust_spatial_attrs_impl(subset_spatial_impl(remote_dataset, region),
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\core\opimpl.py", line 880, in subset_spatial_impl
    return reset_non_spatial(ds, retset)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\core\opimpl.py", line 782, in reset_non_spatial
    for var_name in ds_source.var():
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\xarray\core\common.py", line 54, in wrapped_func
    **kwargs)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\xarray\core\dataset.py", line 2635, in reduce
    **kwargs)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\xarray\core\variable.py", line 1263, in reduce
    data = func(self.data if allow_lazy else self.values,
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\xarray\core\variable.py", line 295, in data
    return self.values
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\xarray\core\variable.py", line 387, in values
    return _as_array_or_item(self._data)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\xarray\core\variable.py", line 211, in _as_array_or_item
    data = np.asarray(data)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\numpy\core\numeric.py", line 501, in asarray
    return array(a, dtype, copy=False, order=order)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\xarray\core\indexing.py", line 624, in __array__
    self._ensure_cached()
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\xarray\core\indexing.py", line 621, in _ensure_cached
    self.array = NumpyIndexingAdapter(np.asarray(self.array))
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\numpy\core\numeric.py", line 501, in asarray
    return array(a, dtype, copy=False, order=order)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\xarray\core\indexing.py", line 602, in __array__
    return np.asarray(self.array, dtype=dtype)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\numpy\core\numeric.py", line 501, in asarray
    return array(a, dtype, copy=False, order=order)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\xarray\core\indexing.py", line 508, in __array__
    return np.asarray(array[self.key], dtype=None)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\xarray\coding\variables.py", line 66, in __getitem__
    return self.func(self.array[key])
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\xarray\coding\variables.py", line 66, in __getitem__
    return self.func(self.array[key])
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\numpy\core\numeric.py", line 501, in asarray
    return array(a, dtype, copy=False, order=order)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\xarray\core\indexing.py", line 508, in __array__
    return np.asarray(array[self.key], dtype=None)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\xarray\backends\netCDF4_.py", line 66, in __getitem__
    array = getitem(self.get_array(), key.tuple)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\xarray\backends\common.py", line 116, in robust_getitem
    return array[key]
  File "netCDF4\_netCDF4.pyx", line 4060, in netCDF4._netCDF4.Variable.__getitem__
  File "netCDF4\_netCDF4.pyx", line 4950, in netCDF4._netCDF4.Variable._get
  File "netCDF4\_netCDF4.pyx", line 1733, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: Access failure`

**Comment by HelenClifton** [comment]
@Evadzi. When I downloaded I did not have any region constraint applied. What happens if you remove the region constraint ?
@forman Please could you assign it to one of the development team to investigate (and remove assignment to me). Thanks !

**Comment by Evadzi** [comment]
@forman I will close this issue because I was able to download the global landcover data as recommended by @HelenClifton . I suspect an issue with the subset function(currently noticed shift in the position of a subset region).
I will run more test to be sure and later create an issue for it (if not already created)

**Comment by Evadzi** [comment]
.....I am still having issues; both global and regional constraints…

Job: Opening data source "esacci.LC.13-yrs.L4.WB.asar.Envisat.Map.4-0.r1"
Message: NetCDF: Access failure
Code: -32003
Method: set_workspace_resource
Exception: RuntimeError

`Traceback (most recent call last):
  File "c:\users\prosper\cci_toolbox_project\cate\cate\util\web\jsonrpchandler.py", line 209, in send_service_method_result
    result = future.result()
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\users\prosper\cci_toolbox_project\cate\cate\util\web\jsonrpchandler.py", line 306, in call_service_method
    result = method(*method_params, monitor=monitor)
  File "c:\users\prosper\cci_toolbox_project\cate\cate\webapi\websocket.py", line 295, in set_workspace_resource
    monitor=monitor)
  File "c:\users\prosper\cci_toolbox_project\cate\cate\core\wsmanag.py", line 320, in set_workspace_resource
    workspace.execute_workflow(res_name=res_name, monitor=monitor)
  File "c:\users\prosper\cci_toolbox_project\cate\cate\core\workspace.py", line 662, in execute_workflow
    self.workflow.invoke_steps(steps, context=self._new_context(), monitor=monitor)
  File "c:\users\prosper\cci_toolbox_project\cate\cate\core\workflow.py", line 627, in invoke_steps
    steps[0].invoke(context=context, monitor=monitor)
  File "c:\users\prosper\cci_toolbox_project\cate\cate\core\workflow.py", line 318, in invoke
    self._invoke_impl(_new_context(context, step=self), monitor=monitor)
  File "c:\users\prosper\cci_toolbox_project\cate\cate\core\workflow.py", line 980, in _invoke_impl
    return_value = self._op(monitor=monitor, **input_values)
  File "c:\users\prosper\cci_toolbox_project\cate\cate\core\op.py", line 216, in __call__
    return_value = self._wrapped_op(**input_values)
  File "c:\users\prosper\cci_toolbox_project\cate\cate\ops\io.py", line 83, in open_dataset
    monitor=monitor)
  File "c:\users\prosper\cci_toolbox_project\cate\cate\core\ds.py", line 675, in open_dataset
    monitor=monitor.child(80))
  File "c:\users\prosper\cci_toolbox_project\cate\cate\ds\esa_cci_odp.py", line 1077, in make_local
    raise e
  File "c:\users\prosper\cci_toolbox_project\cate\cate\ds\esa_cci_odp.py", line 1070, in make_local
    self._make_local(local_ds, time_range, region, var_names, monitor=monitor)
  File "c:\users\prosper\cci_toolbox_project\cate\cate\ds\esa_cci_odp.py", line 948, in _make_local
    remote_dataset.to_netcdf(local_filepath, format='NETCDF4', engine='h5netcdf')
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\core\dataset.py", line 1222, in to_netcdf
    compute=compute)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\backends\api.py", line 718, in to_netcdf
    unlimited_dims=unlimited_dims)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\backends\api.py", line 761, in dump_to_store
    unlimited_dims=unlimited_dims)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\backends\common.py", line 261, in store
    variables, attributes = self.encode(variables, attributes)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\backends\common.py", line 347, in encode
    variables, attributes = cf_encoder(variables, attributes)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\conventions.py", line 573, in cf_encoder
    for k, v in iteritems(variables))
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\conventions.py", line 573, in <genexpr>
    for k, v in iteritems(variables))
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\conventions.py", line 235, in encode_cf_variable
    var = coder.encode(var, name=name)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\coding\times.py", line 389, in encode
    dims, data, attrs, encoding = unpack_for_encoding(variable)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\coding\variables.py", line 99, in unpack_for_encoding
    return var.dims, var.data, var.attrs.copy(), var.encoding.copy()
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\core\variable.py", line 292, in data
    return self.values
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\core\variable.py", line 384, in values
    return _as_array_or_item(self._data)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\core\variable.py", line 208, in _as_array_or_item
    data = np.asarray(data)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\numpy\core\numeric.py", line 501, in asarray
    return array(a, dtype, copy=False, order=order)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\core\indexing.py", line 624, in __array__
    self._ensure_cached()
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\core\indexing.py", line 621, in _ensure_cached
    self.array = NumpyIndexingAdapter(np.asarray(self.array))
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\numpy\core\numeric.py", line 501, in asarray
    return array(a, dtype, copy=False, order=order)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\core\indexing.py", line 602, in __array__
    return np.asarray(self.array, dtype=dtype)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\numpy\core\numeric.py", line 501, in asarray
    return array(a, dtype, copy=False, order=order)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\core\indexing.py", line 508, in __array__
    return np.asarray(array[self.key], dtype=None)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\numpy\core\numeric.py", line 501, in asarray
    return array(a, dtype, copy=False, order=order)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\coding\variables.py", line 69, in __array__
    return self.func(self.array)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\coding\variables.py", line 135, in _apply_mask
    data = np.asarray(data, dtype=dtype)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\numpy\core\numeric.py", line 501, in asarray
    return array(a, dtype, copy=False, order=order)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\coding\variables.py", line 69, in __array__
    return self.func(self.array)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\numpy\core\numeric.py", line 501, in asarray
    return array(a, dtype, copy=False, order=order)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\core\indexing.py", line 508, in __array__
    return np.asarray(array[self.key], dtype=None)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\backends\netCDF4_.py", line 64, in __getitem__
    self._getitem)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\core\indexing.py", line 776, in explicit_indexing_adapter
    result = raw_indexing_method(raw_key.tuple)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\backends\netCDF4_.py", line 76, in _getitem
    array = getitem(original_array, key)
  File "C:\Users\prosper\Miniconda3\envs\cate-env\lib\site-packages\xarray\backends\common.py", line 56, in robust_getitem
    return array[key]
  File "netCDF4\_netCDF4.pyx", line 4119, in netCDF4._netCDF4.Variable.__getitem__
  File "netCDF4\_netCDF4.pyx", line 5036, in netCDF4._netCDF4.Variable._get
  File "netCDF4\_netCDF4.pyx", line 1754, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: Access failure.`

Cate 2.0.0-dev 25, Windows 10
