### ISSUE TITLE
saving workspace to disk

### ISSUE THREAD

**Issue by RainerHollmann** [CCI-Tools/cate#806]
### Expected behavior

*Describe what you expected Cate to do.*
I expect Cate to save my workspace 

### Actual behavior

*Describe what Cate does instead or doesn't do at all.*
Cate stops and does not save the workspace

![save_workspace](https://user-images.githubusercontent.com/44669636/48027354-da3b1480-e148-11e8-9eb3-0d86a9b7992b.PNG)
Traceback (most recent call last):
  File "D:\toolbox\cate-2.0.0.dev20\lib\site-packages\cate\util\web\jsonrpchandler.py", line 209, in send_service_method_result
    result = future.result()
  File "D:\toolbox\cate-2.0.0.dev20\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "D:\toolbox\cate-2.0.0.dev20\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "D:\toolbox\cate-2.0.0.dev20\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\toolbox\cate-2.0.0.dev20\lib\site-packages\cate\util\web\jsonrpchandler.py", line 306, in call_service_method
    result = method(*method_params, monitor=monitor)
  File "D:\toolbox\cate-2.0.0.dev20\lib\site-packages\cate\webapi\websocket.py", line 258, in save_workspace_as
    workspace = self.workspace_manager.save_workspace_as(base_dir, to_dir, monitor=monitor)
  File "D:\toolbox\cate-2.0.0.dev20\lib\site-packages\cate\core\wsmanag.py", line 252, in save_workspace_as
    new_workspace = self.open_workspace(to_dir, monitor=monitor.child(work=50))
  File "D:\toolbox\cate-2.0.0.dev20\lib\site-packages\cate\core\wsmanag.py", line 200, in open_workspace
    workspace.execute_workflow(monitor=monitor.child(50))
  File "D:\toolbox\cate-2.0.0.dev20\lib\site-packages\cate\core\workspace.py", line 662, in execute_workflow
    self.workflow.invoke_steps(steps, context=self._new_context(), monitor=monitor)
  File "D:\toolbox\cate-2.0.0.dev20\lib\site-packages\cate\core\workflow.py", line 632, in invoke_steps
    step.invoke(context=context, monitor=monitor.child(work=1))
  File "D:\toolbox\cate-2.0.0.dev20\lib\site-packages\cate\core\workflow.py", line 318, in invoke
    self._invoke_impl(_new_context(context, step=self), monitor=monitor)
  File "D:\toolbox\cate-2.0.0.dev20\lib\site-packages\cate\core\workflow.py", line 980, in _invoke_impl
    return_value = self._op(monitor=monitor, **input_values)
  File "D:\toolbox\cate-2.0.0.dev20\lib\site-packages\cate\core\op.py", line 216, in __call__
    return_value = self._wrapped_op(**input_values)
  File "D:\toolbox\cate-2.0.0.dev20\lib\site-packages\cate\ops\arithmetics.py", line 108, in ds_arithmetics
    ' implemented.'.format(item[0]))
cate.core.types.ValidationError: Arithmetic operation m not implemented.
### Steps to reproduce the problem

1. create workspace
2. select "save workspace as ..." option
3. select directory,
4. insert name of workspace

### Specifications 
dev20, windows 7
*Provide information such as the version of the project, operating system, or hardware.*

**Comment by forman** [comment]
@RainerHollmann you seem to have an erroneous `arithmetic` step in your workflow. Please remove that first, then save.
