### ISSUE TITLE
External Problem: ODP not available

### ISSUE THREAD

**Issue by Evadzi** [CCI-Tools/cate#807]
### Expected behavior

*I expect Cate to list data available on ODP for download*

### Actual behavior

*ODP connection error*

### Steps to reproduce the problem
1. **uninstall previous version of cate**
2. **delete the .cate folder in your user profile**
3. **install cate 2.0.0 dev-21**

`Job: Load data sources for store "esa_cci_odp"
Message: HTTPSConnectionPool(host='csw.ceda.ac.uk', port=443): Max retries exceeded with url: /geonetwork/srv/eng/csw-CEDA-CCI (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000026DA022F048>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))
Code: -32001
Method: get_data_sources
Exception: requests.exceptions.ConnectionError
Traceback (most recent call last):
  File "C:\Users\prosper\cate-2.0.0.dev21\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\Users\prosper\cate-2.0.0.dev21\lib\site-packages\urllib3\util\connection.py", line 83, in create_connection
    raise err
  File "C:\Users\prosper\cate-2.0.0.dev21\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\prosper\cate-2.0.0.dev21\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Users\prosper\cate-2.0.0.dev21\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "C:\Users\prosper\cate-2.0.0.dev21\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "C:\Users\prosper\cate-2.0.0.dev21\lib\site-packages\urllib3\connection.py", line 284, in connect
    conn = self._new_conn()
  File "C:\Users\prosper\cate-2.0.0.dev21\lib\site-packages\urllib3\connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x0000026DA022F048>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\prosper\cate-2.0.0.dev21\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Users\prosper\cate-2.0.0.dev21\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\prosper\cate-2.0.0.dev21\lib\site-packages\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='csw.ceda.ac.uk', port=443): Max retries exceeded with url: /geonetwork/srv/eng/csw-CEDA-CCI (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000026DA022F048>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\prosper\cate-2.0.0.dev21\lib\site-packages\cate\util\web\jsonrpchandler.py", line 209, in send_service_method_result
    result = future.result()
  File "C:\Users\prosper\cate-2.0.0.dev21\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "C:\Users\prosper\cate-2.0.0.dev21\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\prosper\cate-2.0.0.dev21\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\prosper\cate-2.0.0.dev21\lib\site-packages\cate\util\web\jsonrpchandler.py", line 306, in call_service_method
    result = method(*method_params, monitor=monitor)
  File "C:\Users\prosper\cate-2.0.0.dev21\lib\site-packages\cate\webapi\websocket.py", line 129, in get_data_sources
    data_sources = data_store.query(monitor=monitor)
  File "C:\Users\prosper\cate-2.0.0.dev21\lib\site-packages\cate\ds\esa_cci_odp.py", line 348, in query
    self._init_data_sources()
  File "C:\Users\prosper\cate-2.0.0.dev21\lib\site-packages\cate\ds\esa_cci_odp.py", line 409, in _init_data_sources
    self._load_index()
  File "C:\Users\prosper\cate-2.0.0.dev21\lib\site-packages\cate\ds\esa_cci_odp.py", line 533, in _load_index
    cache_expiration_days=self._index_cache_expiration_days)
  File "C:\Users\prosper\cate-2.0.0.dev21\lib\site-packages\cate\ds\esa_cci_odp.py", line 263, in _load_or_fetch_json
    raise e
  File "C:\Users\prosper\cate-2.0.0.dev21\lib\site-packages\cate\ds\esa_cci_odp.py", line 245, in _load_or_fetch_json
    json_obj = fetch_json_function(*(fetch_json_args or []), **(fetch_json_kwargs or {}))
  File "C:\Users\prosper\cate-2.0.0.dev21\lib\site-packages\cate\ds\esa_cci_odp.py", line 1113, in getrecords
    self._build_catalogue(monitor.child(1))
  File "C:\Users\prosper\cate-2.0.0.dev21\lib\site-packages\cate\ds\esa_cci_odp.py", line 1130, in _build_catalogue
    startposition=start_position, maxrecords=max_records)
  File "C:\Users\prosper\cate-2.0.0.dev21\lib\site-packages\owslib\csw.py", line 376, in getrecords2
    self._invoke()
  File "C:\Users\prosper\cate-2.0.0.dev21\lib\site-packages\owslib\csw.py", line 677, in _invoke
    self.response = util.http_post(request_url, self.request, self.lang, self.timeout, self.username, self.password)
  File "C:\Users\prosper\cate-2.0.0.dev21\lib\site-packages\owslib\util.py", line 395, in http_post
    up = requests.post(url, request, headers=headers, **rkwargs)
  File "C:\Users\prosper\cate-2.0.0.dev21\lib\site-packages\requests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\prosper\cate-2.0.0.dev21\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\prosper\cate-2.0.0.dev21\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\prosper\cate-2.0.0.dev21\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\prosper\cate-2.0.0.dev21\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='csw.ceda.ac.uk', port=443): Max retries exceeded with url: /geonetwork/srv/eng/csw-CEDA-CCI (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000026DA022F048>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)).`

### Specifications 

*Cate 2.0.0 dev 21*
*Windows 10*

**Comment by Evadzi** [comment]
*ODP working now*
