### ISSUE TITLE
Download fails for any datasets from ODP

### ISSUE THREAD

**Issue by forman** [CCI-Tools/cate#811]
Cate is no longer able to download various datasets. It seems, a hyphen character in their dataset ID names are the root cause.

This may be a regression introduced by fixing #343 by @papesci.

![image](https://user-images.githubusercontent.com/206773/48420503-dae03600-e75a-11e8-821d-31078d586531.png)

Or

![image](https://user-images.githubusercontent.com/206773/48420443-bd12d100-e75a-11e8-8118-72efdee3b6e0.png)

with stack traceback:

```
Traceback (most recent call last):
  File "D:\Projects\PycharmProjects\cate\cate\util\web\jsonrpchandler.py", line 209, in send_service_method_result
    result = future.result()
  File "D:\Miniconda3\envs\cate-env\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "D:\Miniconda3\envs\cate-env\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "D:\Miniconda3\envs\cate-env\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Projects\PycharmProjects\cate\cate\util\web\jsonrpchandler.py", line 306, in call_service_method
    result = method(*method_params, monitor=monitor)
  File "D:\Projects\PycharmProjects\cate\cate\webapi\websocket.py", line 292, in set_workspace_resource
    monitor=monitor)
  File "D:\Projects\PycharmProjects\cate\cate\core\wsmanag.py", line 320, in set_workspace_resource
    workspace.execute_workflow(res_name=res_name, monitor=monitor)
  File "D:\Projects\PycharmProjects\cate\cate\core\workspace.py", line 662, in execute_workflow
    self.workflow.invoke_steps(steps, context=self._new_context(), monitor=monitor)
  File "D:\Projects\PycharmProjects\cate\cate\core\workflow.py", line 627, in invoke_steps
    steps[0].invoke(context=context, monitor=monitor)
  File "D:\Projects\PycharmProjects\cate\cate\core\workflow.py", line 318, in invoke
    self._invoke_impl(_new_context(context, step=self), monitor=monitor)
  File "D:\Projects\PycharmProjects\cate\cate\core\workflow.py", line 980, in _invoke_impl
    return_value = self._op(monitor=monitor, **input_values)
  File "D:\Projects\PycharmProjects\cate\cate\core\op.py", line 216, in __call__
    return_value = self._wrapped_op(**input_values)
  File "D:\Projects\PycharmProjects\cate\cate\ops\io.py", line 83, in open_dataset
    monitor=monitor)
  File "D:\Projects\PycharmProjects\cate\cate\core\ds.py", line 588, in open_dataset
    monitor=monitor.child(80))
  File "D:\Projects\PycharmProjects\cate\cate\ds\esa_cci_odp.py", line 997, in make_local
    meta_info=local_meta_info, lock_file=True)
  File "D:\Projects\PycharmProjects\cate\cate\ds\local.py", line 664, in create_data_source
    hint='Use only letters, numbers, dots or underscore in the data source name')
cate.core.types.ValidationError: Unaccepted characters in data source name "local.esacci.SST.day.L4.SSTdepth.multi-sensor.multi-platform.OSTIA.1-1.r1.63032c51-15e3-30ff-9587-24868baf16f4"
```

**Comment by papesci** [comment]
the char minus wasn't included in the accepted char. the branch (https://github.com/CCI-Tools/cate/tree/811-pp-dataset-name-check) fix it.
