### ISSUE TITLE
Landcover/Scalar datasets don't support chunk/filter options

### ISSUE THREAD

**Issue by Evadzi** [CCI-Tools/cate#829]
### Expected behavior

*Ingest LCCS data using ODP*

### Actual behavior

*Unsuccessful*

### Steps to reproduce the problem

1. *select  product (esacci.LC.5-yrs.L4.LCCS.multi-sensor.multi-platform.Map.1-6-1.r1)* 
2. *specify lon -10 10, lat -10 10 as ROI* 
3. *error message*----
```Job: Opening data source "esacci.LC.5-yrs.L4.LCCS.multi-sensor.multi-platform.Map.1-6-1.r1"
Message: Scalar datasets don't support chunk/filter options
Code: -32003
Method: set_workspace_resource
Exception: TypeError

Traceback (most recent call last):
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\util\web\jsonrpchandler.py", line 209, in send_service_method_result
    result = future.result()
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\util\web\jsonrpchandler.py", line 306, in call_service_method
    result = method(*method_params, monitor=monitor)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\webapi\websocket.py", line 292, in set_workspace_resource
    monitor=monitor)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\core\wsmanag.py", line 320, in set_workspace_resource
    workspace.execute_workflow(res_name=res_name, monitor=monitor)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\core\workspace.py", line 662, in execute_workflow
    self.workflow.invoke_steps(steps, context=self._new_context(), monitor=monitor)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\core\workflow.py", line 627, in invoke_steps
    steps[0].invoke(context=context, monitor=monitor)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\core\workflow.py", line 318, in invoke
    self._invoke_impl(_new_context(context, step=self), monitor=monitor)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\core\workflow.py", line 980, in _invoke_impl
    return_value = self._op(monitor=monitor, **input_values)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\core\op.py", line 216, in __call__
    return_value = self._wrapped_op(**input_values)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\ops\io.py", line 83, in open_dataset
    monitor=monitor)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\core\ds.py", line 603, in open_dataset
    monitor=monitor.child(80))
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\ds\esa_cci_odp.py", line 1008, in make_local
    raise e
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\ds\esa_cci_odp.py", line 1001, in make_local
    self._make_local(local_ds, time_range, region, var_names, monitor=monitor)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\cate\ds\esa_cci_odp.py", line 881, in _make_local
    remote_dataset.to_netcdf(local_filepath, format='NETCDF4', engine='h5netcdf')
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\xarray\core\dataset.py", line 1222, in to_netcdf
    compute=compute)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\xarray\backends\api.py", line 718, in to_netcdf
    unlimited_dims=unlimited_dims)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\xarray\backends\api.py", line 761, in dump_to_store
    unlimited_dims=unlimited_dims)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\xarray\backends\common.py", line 266, in store
    unlimited_dims=unlimited_dims)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\xarray\backends\common.py", line 304, in set_variables
    name, v, check, unlimited_dims=unlimited_dims)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\xarray\backends\h5netcdf_.py", line 218, in prepare_variable
    fillvalue=fillvalue, **kwargs)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\h5netcdf\core.py", line 431, in create_variable
    fillvalue, **kwargs)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\h5netcdf\core.py", line 411, in _create_child_variable
    **kwargs)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\h5py\_hl\group.py", line 116, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\h5py\_hl\dataset.py", line 120, in make_new_dset
    shuffle, fletcher32, maxshape, scaleoffset)
  File "C:\Users\prosper\cate-2.0.0.dev22\lib\site-packages\h5py\_hl\filters.py", line 83, in generate_dcpl
    raise TypeError("Scalar datasets don't support chunk/filter options")
TypeError: Scalar datasets don't support chunk/filter options```

 
### Specifications 
*Windows 10, cate desktop 2.0.0-dev.24*

**Comment by forman** [comment]
Damn, I fear, this is a regression of https://github.com/CCI-Tools/cate/pull/828 that attempts to fix #823 and others.
