### ISSUE TITLE
cate-webapi-start cli doesn't start as expected. 

### ISSUE THREAD

**Issue by suvarchal** [CCI-Tools/cate#875]
cate-webapi-start doesn't start the service and on first connection to the service raises 5xx server error and  following error in terminal

```
cate-webapi: started service, listening on localhost:55347
tornado.application - ERROR - Uncaught exception GET / (::1)
HTTPServerRequest(protocol='http', host='localhost:55347', method='GET', uri='/', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/home/suvarchal/miniconda3/envs/cate-env/lib/python3.7/site-packages/tornado/web.py", line 1701, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/suvarchal/.local/lib/python3.7/site-packages/cate-2.1.0.dev0-py3.7.egg/cate/webapi/start.py", line 78, in get
    user_root_mode = self.application.root_dir is not None
AttributeError: 'Application' object has no attribute 'root_dir'
```

**Comment by suvarchal** [comment]
#876 Fixes this so closing now.
