### ISSUE TITLE
Cate 2.0.0 Desktop not Running on MacOS Catalina

### ISSUE THREAD

**Issue by cjnankervis** [CCI-Tools/cate#893]
I am trying to install Cate 2.0.0 Desktop on a Mac - with Anaconda 3.7 already installed. The software appears to install correctly, however it will not then load correctly (reporting connection refused) with the error message indicating that some libraries or Python modules are not working as expected.

What could be causing this? Is it a conflict between the Python installations (Anaconda was already installed on my machine). Is there an easy solution?

The error message in the log reads as follows:

[2020-06-08 13:11:09.180] [info] Waiting for response from Cate service http://localhost:9090/
[2020-06-08 13:11:09.182] [info] No response from Cate service after 6.59 seconds: Error: connect ECONNREFUSED 127.0.0.1:9090
[2020-06-08 13:11:09.182] [info] Splash says: Waiting for Cate service (6.59s)
[2020-06-08 13:11:09.578] [error] cate-webapi: Traceback (most recent call last):
  File "/Users/Chris-Win/cate-2.0.0/bin/cate-webapi-start", line 7, in <module>
    from cate.webapi.start import main
  File "/Users/Chris-Win/cate-2.0.0/lib/python3.7/site-packages/cate/webapi/start.py", line 54, in <module>
    from cate.core.types import ValidationError
  File "/Users/Chris-Win/cate-2.0.0/lib/python3.7/site-packages/cate/core/__init__.py", line 41, in <module>
    from .ds import DataStore, DataSource, open_dataset, find_data_sources, DATA_STORE_REGISTRY
  File "/Users/Chris-Win/cate-2.0.0/lib/python3.7/site-packages/cate/core/ds.py", line 92, in <module>
    from .cdm import Schema, get_lon_dim_name, get_lat_dim_name
  File "/Users/Chris-Win/cate-2.0.0/lib/python3.7/site-packages/cate/core/cdm.py", line 116, in <module>
    from .opimpl import get_lat_dim_name_impl, get_lon_dim_name_impl
  File "/Users/Chris-Win/cate-2.0.0/lib/python3.7/site-packages/cate/core/opimpl.py", line 33, in <module>
    from .types import PolygonLike, ValidationError
  File "/Users/Chris-Win/cate-2.0.0/lib/python3.7/site-packages/cate/core/types.py", line 44, in <module>
    import geopandas
  File "/Users/Chris-Win/cate-2.0.0/lib/python3.7/site-packages/geopandas/__init__.py", line 4, in <module>
    from geopandas.io.file import read_file
  File "/Users/Chris-Win/cate-2.0.0/lib/python3.7/site-packages/geopandas/io/file.py", line 3, in <module>
    import fiona
  File "/Users/Chris-Win/cate-2.0.0/lib/python3.7/site-packages/fiona/__init__.py", line 83, in <module>
    from fiona.collection import BytesCollection, Collection
  File "/Users/Chris-Win/cate-2.0.0/lib/python3.7/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: dlopen(/Users/Chris-Win/cate-2.0.0/lib/python3.7/site-packages/fiona/ogrext.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libpoppler.76.dylib
  Referenced from: /Users/Chris-Win/cate-2.0.0/lib/libgdal.20.dylib
  Reason: image not found

**Comment by forman** [comment]
We are no longer supporting Cate Desktop
