### ISSUE TITLE
Support GHG datasets in Zarr Data Store

### ISSUE THREAD

**Issue by TonioF** [CCI-Tools/cate#982]
The Zarr Data Store contains data from the ODP that has been converted into the zarr format. There are two GHG datasets in the Zarr data store. For the purposes of this issue, we say that a dataset is supported when
1. it can be opened in cate
2. it can be opened in cate with a spatial subset
3. its content can be written to disk
4. its data can be displayed in cate

The GHG datasets cannot be opened at all. Their respective tracebacks are:

[2021-04-29 08:54:15] Request: 
open_dataset(datasetid=ESACCI-GHG-L2-CO2-SCIAMACHY-WFMD-2002-2012-fv1.zarr, time_range=('2002-10-01', '2012-04-08'), var_names=['state_number', 'state_number'], region=None)

Traceback (most recent call last):
  File "test_cci_data_support.py", line 306, in test_open_ds
    dataset, _ = open_dataset(dataset_id=data_id,
  File "/home/users/tfincke/Projects/cate/cate/core/ds.py", line 432, in open_dataset
    dataset = select_subset(dataset, **subset_args)
  File "/home/users/tfincke/Projects/xcube/xcube/core/select.py", line 39, in select_subset
    dataset = select_temporal_subset(dataset, time_range=time_range)
  File "/home/users/tfincke/Projects/xcube/xcube/core/select.py", line 116, in select_temporal_subset
    raise ValueError(f'cannot compute temporal subset: variable "{time_name}" not found in dataset')
ValueError: cannot compute temporal subset: variable "time" not found in dataset

and 

[2021-04-29 08:52:44] Request: 
open_dataset(datasetid=ESACCI-GHG-L2-CH4-SCIAMACHY-WFMD-2002-2011-fv1.zarr, time_range=('2002-10-01', '2011-12-31'), var_names=['time', 'xch4_quality_flag'], region=None)

Traceback (most recent call last):
  File "test_cci_data_support.py", line 306, in test_open_ds
    dataset, _ = open_dataset(dataset_id=data_id,
  File "/home/users/tfincke/Projects/cate/cate/core/ds.py", line 432, in open_dataset
    dataset = select_subset(dataset, **subset_args)
  File "/home/users/tfincke/Projects/xcube/xcube/core/select.py", line 39, in select_subset
    dataset = select_temporal_subset(dataset, time_range=time_range)
  File "/home/users/tfincke/Projects/xcube/xcube/core/select.py", line 127, in select_temporal_subset
    return dataset.sel({time_name or 'time': slice(time_1, time_2)})
  File "/home/users/tfincke/miniconda3/envs/xcube/lib/python3.8/site-packages/xarray/core/dataset.py", line 2230, in sel
    pos_indexers, new_indexes = remap_label_indexers(
  File "/home/users/tfincke/miniconda3/envs/xcube/lib/python3.8/site-packages/xarray/core/coordinates.py", line 416, in remap_label_indexers
    pos_indexers, new_indexes = indexing.remap_label_indexers(
  File "/home/users/tfincke/miniconda3/envs/xcube/lib/python3.8/site-packages/xarray/core/indexing.py", line 254, in remap_label_indexers
    dim_indexers = get_dim_indexers(data_obj, indexers)
  File "/home/users/tfincke/miniconda3/envs/xcube/lib/python3.8/site-packages/xarray/core/indexing.py", line 220, in get_dim_indexers
    raise ValueError(f"dimensions or multi-index levels {invalid!r} do not exist")
ValueError: dimensions or multi-index levels ['time'] do not exist

**Comment by forman** [comment]
Cate can open these datasets, but cannot

- create spatial subsets nor image tiles because data is 1D
- create temporal subset because the `time` variable's dimension name is `sounding_dim`

![image](https://user-images.githubusercontent.com/206773/118681351-ce436980-b7ff-11eb-8183-56c321c326da.png)
